
services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /app/var
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0

  db:
    image: postgres:17
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony

volumes:
  pgdata:
