nelmio_cors:
    defaults:
        allow_credentials: true # Permet l'envoi de cookies
        allow_origin: ['*']  # URL de ton frontend (remplace avec l'URL correcte)
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    paths:
        '^/api/':
            allow_origin: ['*'] 