security:
    password_hashers:
        App\Entity\Users:
            algorithm: argon2id
        App\Controller\Admin\UserscrudController:
            algorithm: argon2id
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

            logout:
                path: /logout
                target: /login

        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~       

            logout:
                path: /logout
                target: /login
            
            
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        
